export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";

export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const USER_ENTRY_BEGIN = "USER_ENTRY_BEGIN";
export const USER_ENTRY_ERROR = "USER_ENTRY_ERROR";
export const USER_ENTRY_SUCCESS = "USER_ENTRY_SUCCESS";

export const KEEP_SCANNING = "KARO BHAI SCAN KARO";

export const GET_CATEGORIES_BEGIN = "GET CATEGORIES BEGIN";
export const GET_CATEGORIES_SUCCESS = "GET CATEGORIES SUCCESS";
export const GET_CATEGORIES_ERROR = "GET CATEGORIES ERROR";

export const REGISTER_PROSHOW_BEGIN = "REGISTER_PROSHOW_BEGIN";
export const REGISTER_PROSHOW_SUCCESS = "REGISTER_PROSHOW_SUCCESS";
export const REGISTER_PROSHOW_ERROR = "REGISTER_PROSHOW_ERROR";

export const GET_EVENTS_BEGIN = "GET_EVENTS_BEGIN";
export const GET_EVENTS_ERROR = "GET_EVENTS_ERROR";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";

export const SET_TEAM_NUMBER = "SET_TEAM_NUMBER";
export const SET_EVENT_ID = "SET_EVENT_ID";

// export const setTeamNumber = (teamNumber) => ({
//   type: SET_TEAM_NUMBER,
//   payload: teamNumber,
// });

// export const setEventID = (eventID) => ({
//   type: SET_EVENT_ID,
//   payload: eventID,
// });
