export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";

export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const USER_ENTRY_BEGIN = "USER_ENTRY_BEGIN";
export const USER_ENTRY_ERROR = "USER_ENTRY_ERROR";
export const USER_ENTRY_SUCCESS = "USER_ENTRY_SUCCESS";

export const KEEP_SCANNING = "KARO BHAI SCAN KARO";

export const GET_CATEGORIES_BEGIN = "GET CATEGORIES BEGIN";
export const GET_CATEGORIES_SUCCESS = "GET CATEGORIES SUCCESS";
export const GET_CATEGORIES_ERROR = "GET CATEGORIES ERROR";
